#ifndef STUDENT_CODE_H
#define STUDENT_CODE_H
const char* student_python_code = 
"# =========================================================================\n"
"# UCT Micromouse - Milestone 0: Run Straight (Reference)\n"
"# =========================================================================\n"
"# ALGORITHM:\n"
"#   Drive forward for a fixed distance (e.g., 2.0 metres) using\n"
"#   closed-loop feedback.\n"
"#\n"
"#   Straight phase  — Fused encoder + gyro control.\n"
"#       Encoder balance (P-controller) compensates for motor speed asymmetry.\n"
"#       Gyro heading integration corrects residual drift that encoder-only\n"
"#       control cannot eliminate (steady-state P-error + wheel slip).\n"
"#       Both corrections are summed into each motor PWM command.\n"
"#\n"
"# =========================================================================\n"
"\n"
"import uct_mouse\n"
"\n"
"# ---------------------------------------------------------------------------\n"
"# Tuning constants\n"
"# ---------------------------------------------------------------------------\n"
"DISTANCE_M      = 1.00          # metres to drive straight\n"
"TICKS_PER_M     = 41            # encoder ticks per metre — matches simulator\n"
"TARGET_TICKS    = int(DISTANCE_M * TICKS_PER_M)\n"
"\n"
"FWD_PWM         = 45            # base forward PWM (–100 … 100)\n"
"\n"
"KP_BALANCE      = 0.5           # P-gain: corrects left/right encoder imbalance during straight\n"
"KH_HEADING      = 1.5           # P-gain: corrects accumulated heading drift via gyro integration\n"
"\n"
"VERBOSE         = True          # print debug info during run\n"
"\n"
"# ---------------------------------------------------------------------------\n"
"# Helpers to read sensors cleanly\n"
"# ---------------------------------------------------------------------------\n"
"\n"
"def _sensors():\n"
"    \"\"\"Returns (lenc, renc, gyro_dps) from the current shadow state.\"\"\"\n"
"    lenc, renc = uct_mouse.get_encoders()\n"
"    raw = uct_mouse._mouse.get_sensors()\n"
"    gyro = raw.get('gyro', 0.0)   # gyro Z-axis in degrees/second\n"
"    return lenc, renc, gyro\n"
"\n"
"# ---------------------------------------------------------------------------\n"
"# Movement primitive: drive straight\n"
"# ---------------------------------------------------------------------------\n"
"\n"
"def drive_straight(distance_m: float):\n"
"    \"\"\"\n"
"    Drive forward exactly distance_m metres using fused encoder + gyro control.\n"
"    \"\"\"\n"
"    lenc0, renc0, _ = _sensors()\n"
"    target = int(distance_m * TICKS_PER_M)\n"
"    dt_s   = 0.050          # physics step (20 Hz simulator)\n"
"    heading_drift = 0.0     # accumulated heading error in degrees (+ = drifting CCW/left)\n"
"\n"
"    if VERBOSE:\n"
"        print(f\"Driving {distance_m} m  (target {target} ticks)...\")\n"
"\n"
"    while True:\n"
"        lenc, renc, gyro_dps = _sensors()\n"
"        dl = lenc - lenc0\n"
"        dr = renc - renc0\n"
"        avg = (dl + dr) / 2.0\n"
"\n"
"        if avg >= target:\n"
"            break\n"
"\n"
"        # Integrate heading drift (CCW = positive gyro = curving left)\n"
"        heading_drift += gyro_dps * dt_s\n"
"\n"
"        # Term 1: encoder balance — keeps arc lengths equal\n"
"        cross_error = dl - dr\n"
"        enc_correction = KP_BALANCE * cross_error\n"
"\n"
"        # Term 2: gyro heading — drives heading drift back to zero\n"
"        #   drift > 0 → curving left → increase right, decrease left\n"
"        heading_correction = KH_HEADING * heading_drift\n"
"\n"
"        l_pwm = int(FWD_PWM - enc_correction + heading_correction)\n"
"        r_pwm = int(FWD_PWM + enc_correction - heading_correction)\n"
"\n"
"        # Clamp to safe range\n"
"        l_pwm = max(15, min(75, l_pwm))\n"
"        r_pwm = max(15, min(75, r_pwm))\n"
"\n"
"        uct_mouse.set_motors(l_pwm, r_pwm)\n"
"\n"
"    # Hard stop\n"
"    uct_mouse.set_motors(0, 0)\n"
"    lenc_f, renc_f, _ = _sensors()\n"
"    if VERBOSE:\n"
"        dl_f = lenc_f - lenc0\n"
"        dr_f = renc_f - renc0\n"
"        print(f\"Done. Ticks L={dl_f}  R={dr_f}  \"\n"
"              f\"imbalance={abs(dl_f-dr_f)} ticks  heading_drift={heading_drift:.1f}°\")\n"
"\n"
"    uct_mouse.delay_ms(120)\n"
"\n"
"# ---------------------------------------------------------------------------\n"
"# Main entry point\n"
"# ---------------------------------------------------------------------------\n"
"\n"
"def run_straight():\n"
"    if not uct_mouse.init():\n"
"        print(\"Initialization failed.\")\n"
"        return\n"
"\n"
"    # Default polarity configurations must be hardcoded in code rather than read from external files\n"
"    uct_mouse.set_polarity(1, 1)\n"
"\n"
"    print(\"=== Milestone 0: Run Straight ===\")\n"
"    print(f\"  Encoder target : {TARGET_TICKS} ticks  ({TICKS_PER_M} ticks/m)\")\n"
"    print()\n"
"\n"
"    drive_straight(DISTANCE_M)\n"
"\n"
"    # Final stop\n"
"    uct_mouse.set_motors(0, 0)\n"
"    print()\n"
"    print(\"=== Milestone 0 Complete! ===\")\n"
"\n"
"try:\n"
"    __name__\n"
"except NameError:\n"
"    __name__ = \"__main__\"\n"
"\n"
"if __name__ == \"__main__\":\n"
"    run_straight()\n"
;
#endif
