#ifndef STUDENT_CODE_H
#define STUDENT_CODE_H
const char* student_python_code = 
"import uct_mouse\n"
"import sys\n"
"\n"
"def main():\n"
"    # Initialize the connection to PC Simulator or Physical Hardware\n"
"    # This also re-initializes the SSD1306 OLED and VL53L0X ToF sensors on physical boot.\n"
"    uct_mouse.init()\n"
"    uct_mouse.set_polarity(1, 1)\n"
"    \n"
"    print(\"--- UCT Mouse Idle Telemetry Test ---\")\n"
"    \n"
"    while True:\n"
"        # Read sensor values\n"
"        tof_l, tof_al, tof_c, tof_ar, tof_r = uct_mouse.get_tof()\n"
"        gyro = uct_mouse.get_gyro()\n"
"        vbatt = uct_mouse.get_vbatt()\n"
"        lenc, renc = uct_mouse.get_encoders()\n"
"        \n"
"        # Print telemetry frames to standard output (readable via serial VCP)\n"
"        print(\"ToF: L={:<4} C={:<4} R={:<4} | Gyro: {:<6.3f} | Batt: {:<4.2f}V | Enc: L={:<5} R={:<5}\".format(\n"
"            tof_l, tof_c, tof_r, gyro, vbatt, lenc, renc\n"
"        ))\n"
"        \n"
"        # update display and wait 100ms (sensor registers refresh inside delay_ms)\n"
"        uct_mouse.delay_ms(100)\n"
"\n"
"if __name__ == \"__main__\":\n"
"    try:\n"
"        main()\n"
"    except Exception as e:\n"
"        try:\n"
"            uct_mouse.set_motors(0, 0)\n"
"        except:\n"
"            pass\n"
"        \n"
"        # Avoid semihosting lockup trap\n"
"        # try:\n"
"        #     with open('error_log.txt', 'w') as f:\n"
"        #         sys.print_exception(e, f)\n"
"        # except:\n"
"        #     pass\n"
"        raise e\n"
;
#endif
