/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "# =========================================================================\n"
            "# UCT Micromouse - Milestone 0: Run Straight (Reference)\n"
            "# =========================================================================\n"
            "# ALGORITHM:\n"
            "#   Drive forward for a fixed distance (e.g., 2.0 metres) using\n"
            "#   closed-loop feedback.\n"
            "#\n"
            "#   Straight phase  — Fused encoder + gyro control.\n"
            "#       Encoder balance (P-controller) compensates for motor speed asymmetry.\n"
            "#       Gyro heading integration corrects residual drift that encoder-only\n"
            "#       control cannot eliminate (steady-state P-error + wheel slip).\n"
            "#       Both corrections are summed into each motor PWM command.\n"
            "#\n"
            "# =========================================================================\n"
            "import uct_mouse\n"
            "# ---------------------------------------------------------------------------\n"
            "# Tuning constants\n"
            "# ---------------------------------------------------------------------------\n"
            "DISTANCE_M      = 1.00          # metres to drive straight\n"
            "TICKS_PER_M     = 41            # encoder ticks per metre — matches simulator\n"
            "TARGET_TICKS    = int(DISTANCE_M * TICKS_PER_M)\n"
            "FWD_PWM         = 45            # base forward PWM (–100 … 100)\n"
            "KP_BALANCE      = 0.5           # P-gain: corrects left/right encoder imbalance during straight\n"
            "KH_HEADING      = 1.5           # P-gain: corrects accumulated heading drift via gyro integration\n"
            "VERBOSE         = True          # print debug info during run\n"
            "# ---------------------------------------------------------------------------\n"
            "# Helpers to read sensors cleanly\n"
            "# ---------------------------------------------------------------------------\n"
            "def _sensors():\n"
            "    lenc, renc = uct_mouse.get_encoders()\n"
            "    gyro = uct_mouse.get_gyro()   # gyro Z-axis in degrees/second\n"
            "    return lenc, renc, gyro\n"
            "# ---------------------------------------------------------------------------\n"
            "# Movement primitive: drive straight\n"
            "# ---------------------------------------------------------------------------\n"
            "def drive_straight(distance_m: float):\n"
            "    lenc0, renc0, _ = _sensors()\n"
            "    target = int(distance_m * TICKS_PER_M)\n"
            "    dt_s   = 0.050          # physics step (20 Hz simulator)\n"
            "    heading_drift = 0.0     # accumulated heading error in degrees (+ = drifting CCW/left)\n"
            "    if VERBOSE:\n"
            "        print(\"Driving %f m  (target %d ticks)...\" % (distance_m, target))\n"
            "    while True:\n"
            "        lenc, renc, gyro_dps = _sensors()\n"
            "        dl = lenc - lenc0\n"
            "        dr = renc - renc0\n"
            "        avg = (dl + dr) / 2.0\n"
            "        if avg >= target:\n"
            "            break\n"
            "        # Integrate heading drift (CCW = positive gyro = curving left)\n"
            "        heading_drift += gyro_dps * dt_s\n"
            "        # Term 1: encoder balance — keeps arc lengths equal\n"
            "        cross_error = dl - dr\n"
            "        enc_correction = KP_BALANCE * cross_error\n"
            "        # Term 2: gyro heading — drives heading drift back to zero\n"
            "        #   drift > 0 → curving left → increase right, decrease left\n"
            "        heading_correction = KH_HEADING * heading_drift\n"
            "        l_pwm = int(FWD_PWM - enc_correction + heading_correction)\n"
            "        r_pwm = int(FWD_PWM + enc_correction - heading_correction)\n"
            "        # Clamp to safe range\n"
            "        l_pwm = max(15, min(75, l_pwm))\n"
            "        r_pwm = max(15, min(75, r_pwm))\n"
            "        uct_mouse.set_motors(l_pwm, r_pwm)\n"
            "        uct_mouse.delay_ms(50)  # Refresh sensors and update the OLED screen!\n"
            "    # Hard stop\n"
            "    uct_mouse.set_motors(0, 0)\n"
            "    lenc_f, renc_f, _ = _sensors()\n"
            "    if VERBOSE:\n"
            "        dl_f = lenc_f - lenc0\n"
            "        dr_f = renc_f - renc0\n"
            "        print(\"Done. Ticks L=%d  R=%d  imbalance=%d ticks  heading_drift=%.1f°\" %              (dl_f, dr_f, abs(dl_f-dr_f), heading_drift))\n"
            "    uct_mouse.delay_ms(120)\n"
            "# ---------------------------------------------------------------------------\n"
            "# Main entry point\n"
            "# ---------------------------------------------------------------------------\n"
            "def run_straight():\n"
            "    if not uct_mouse.init():\n"
            "        print(\"Initialization failed.\")\n"
            "        return\n"
            "    # Default polarity configurations must be hardcoded in code rather than read from external files\n"
            "    uct_mouse.set_polarity(1, 1)\n"
            "    print(\"=== Milestone 0: Run Straight ===\")\n"
            "    print(\"  Encoder target : %d ticks  (%d ticks/m)\" % (TARGET_TICKS, TICKS_PER_M))\n"
            "    print()\n"
            "    drive_straight(DISTANCE_M)\n"
            "    # Final stop\n"
            "    uct_mouse.set_motors(0, 0)\n"
            "    print()\n"
            "    print(\"=== Milestone 0 Complete! ===\")\n"
            "try:\n"
            "    __name__\n"
            "except NameError:\n"
            "    __name__ = \"__main__\"\n"
            "if __name__ == \"__main__\":\n"
            "    run_straight()\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

