/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "import uct_mouse\n"
            "import sys\n"
            "def main():\n"
            "    # Initialize the connection to PC Simulator or Physical Hardware\n"
            "    # This also re-initializes the SSD1306 OLED and VL53L0X ToF sensors on physical boot.\n"
            "    uct_mouse.init()\n"
            "    uct_mouse.set_polarity(1, 1)\n"
            "    \n"
            "    print(\"--- UCT Mouse Idle Telemetry Test ---\")\n"
            "    \n"
            "    while True:\n"
            "        # Read sensor values\n"
            "        tof_l, tof_al, tof_c, tof_ar, tof_r = uct_mouse.get_tof()\n"
            "        gyro = uct_mouse.get_gyro()\n"
            "        vbatt = uct_mouse.get_vbatt()\n"
            "        lenc, renc = uct_mouse.get_encoders()\n"
            "        \n"
            "        # Print telemetry frames to standard output (readable via serial VCP)\n"
            "        print(\"ToF: L={:<4} C={:<4} R={:<4} | Gyro: {:<6.3f} | Batt: {:<4.2f}V | Enc: L={:<5} R={:<5}\".format(            tof_l, tof_c, tof_r, gyro, vbatt, lenc, renc        ))\n"
            "        \n"
            "        # update display and wait 100ms (sensor registers refresh inside delay_ms)\n"
            "        uct_mouse.delay_ms(100)\n"
            "if __name__ == \"__main__\":\n"
            "    try:\n"
            "        main()\n"
            "    except Exception as e:\n"
            "        try:\n"
            "            uct_mouse.set_motors(0, 0)\n"
            "        except:\n"
            "            pass\n"
            "        \n"
            "        # Avoid semihosting lockup trap\n"
            "        # try:\n"
            "        #     with open('error_log.txt', 'w') as f:\n"
            "        #         sys.print_exception(e, f)\n"
            "        # except:\n"
            "        #     pass\n"
            "        raise e\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

