/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#include "PikaMain.h"
#include <stdio.h>
#include <stdlib.h>

volatile PikaObj *__pikaMain;
PikaObj *pikaPythonInit(void){
    pika_platform_printf("======[pikapython packages installed]======\r\n");
    pika_printVersion();
    pika_platform_printf("PikaStdLib\r\n");
    pika_platform_printf("pikascript-core\r\n");
    pika_platform_printf("===========================================\r\n");
    PikaObj* pikaMain = newRootObj("pikaMain", New_PikaMain);
    __pikaMain = pikaMain;
    extern unsigned char pikaModules_py_a[];
    obj_linkLibrary(pikaMain, pikaModules_py_a);
#if PIKA_INIT_STRING_ENABLE
    obj_run(pikaMain,
            "# main.py -- UCT Micromouse Default Telemetry Streamer\n"
            "import uct_mouse\n"
            "# Initialize hardware (wakes OLED screen and sensor peripherals)\n"
            "uct_mouse.init()\n"
            "uct_mouse.set_motors(0, 0)\n"
            "print(\"--- UCT Micromouse Online ---\")\n"
            "print(\"Streaming live telemetry over USB serial. Replace main.py with your code!\")\n"
            "while True:\n"
            "    tof = uct_mouse.get_tof()\n"
            "    enc = uct_mouse.get_encoders()\n"
            "    vbatt = uct_mouse.get_vbatt()\n"
            "    gyro = uct_mouse.get_gyro()\n"
            "    print(\"VBatt: %.2fV | Gyro: %+.2f dps | Enc: (%d, %d) | ToF: %s\" % (\n"
            "        vbatt, gyro, enc[0], enc[1], str(tof)\n"
            "    ))\n"
            "    uct_mouse.delay_ms(250)\n"
            "\n");
#else 
    obj_runModule((PikaObj*)pikaMain, "main");
#endif
    return pikaMain;
}

